{% set name = "pyfume" %}
{% set version = "0.2.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyFUME-{{ version }}.tar.gz
  sha256: b83d481c5c8d77dcafddec873d9e2983a5f6fab2d3639b18b10cacb885dbbdf0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - scipy
    - numpy
    - simpful
    - fst-pso
    - pandas

test:
  imports:
    - pyfume
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CaroFuchs/pyFUME
  summary: A Python package for fuzzy model estimation
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bgruening
